language: objective-c
osx_image: beta-xcode6.3

xcode_workspace: Example/KRLCollectionViewGridLayoutDemo.xcworkspace
xcode_scheme: KRLCollectionViewGridLayoutDemo
xcode_sdk: iphonesimulator

before_install:
  - gem update cocoapods -N
  - brew update
  - brew upgrade xctool
install:
  - cd Example
  - pod install
  - cd ..