# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage
osx_image: xcode7.1

language: objective-c
before_install:
- gem install cocoapods --no-rdoc --no-ri --no-document --quiet # Since Travis is not always on latest version
install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- cd Example
- pod install
- set -o pipefail && xcodebuild test -workspace KRLCollectionViewGridLayoutDemo.xcworkspace -scheme KRLCollectionViewGridLayoutDemo -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6' ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty -c
- cd ..
- pod lib lint --quick

after_success:
- bash <(curl -s https://codecov.io/bash)
